#![no_std]
#![no_main]

//! AegisToken Universal RP2350 Firmware — entry point.
//!
//! Phase 5: the committed configuration is persisted to flash with a
//! power-fail-safe two-slot store and reloaded (with fallback) on boot. The
//! device root key can be read from OTP for sealed secret storage.

use aegis_core::authenticator::{self, CredentialManagementRequest, MemoryCredentialStore};
use aegis_core::configuration::{DeviceConfig, LedBehavior, ValidationContext};
use aegis_core::ctap2::{self, Ctap2Request};
use aegis_core::ctaphid::{self, Assembler, CtapHidCommand, CtapHidError};
use aegis_core::lifecycle::LifecycleState;
use aegis_core::management_protocol::{ManagementCommand, ManagementService};
use aegis_core::pin::{
    ClientPin, ClientPinRequest, SUB_GET_KEY_AGREEMENT, SUB_GET_PIN_TOKEN,
    SUB_GET_PIN_UV_AUTH_TOKEN_WITH_PERMISSIONS, SUB_GET_RETRIES, SUB_SET_PIN,
};
use aegis_core::presence::PresenceTiming;
use aegis_core::storage::ConfigStorage;
use aegis_core::traits::Rp2350Hardware;
use aegis_core::u2f;
use aegis_core::update::{self, UpdateSession};
use board_generic_rp2350::presence::await_bootsel;
use board_generic_rp2350::rng::HardwareRng;
use board_generic_rp2350::usb::{
    FidoReader, FidoWriter, KeyboardWriter, ManagementReader, ManagementWriter, RpUsb, Usb,
};
use board_generic_rp2350::{Board, BoardProfile, Platform, embassy_rp};
use defmt::info;
use defmt_rtt as _;
use embassy_executor::Spawner;
use embassy_futures::join::{join, join3};
use embassy_futures::select::{Either, select};
use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::signal::Signal;
use embassy_time::{Duration, Timer};
use embassy_usb::UsbDevice;
use panic_probe as _;

mod selftest;

/// Last CTAP2 command byte received on the FIDO interface (diagnostics).
static LAST_CTAP_COMMAND: core::sync::atomic::AtomicU8 = core::sync::atomic::AtomicU8::new(0);
/// Last CTAP2 status byte returned on the FIDO interface (diagnostics).
static LAST_CTAP_STATUS: core::sync::atomic::AtomicU8 = core::sync::atomic::AtomicU8::new(0);

/// Signalled when the host requests a soft detach over the Management channel;
/// the USB supervisor awaits it before disabling the peripheral.
static DETACH: Signal<CriticalSectionRawMutex, ()> = Signal::new();

/// Vendor Management HID command: return the last FIDO command/status pair.
const CMD_GET_LAST_FIDO_STATUS: u8 = 0x14;

/// Flash capacity known at build time, used to size the flash driver.
const FLASH_SIZE: usize = 2 * 1024 * 1024;

/// Base offset of the configuration slots.
const CONFIG_BASE: u32 = 0x100000;

/// Size of one storage slot; must match the flash erase granularity.
const SLOT_SIZE: u32 = 4096;

/// Watchdog timeout while the main loop is running.
const WATCHDOG_TIMEOUT: Duration = Duration::from_millis(5_000);

/// CTAPHID capabilities advertised at INIT: WINK, CBOR (CTAP2) and NMSG
/// (CTAP1/U2F).
const CTAPHID_CAPABILITIES: u8 = 0x0D;

/// Presence timing used for FIDO operations.
const PRESENCE_TIMING: PresenceTiming = PresenceTiming {
    debounce_ms: 20,
    timeout_ms: 15_000,
};

/// Base offset of the firmware staging region (separate from the running image).
const STAGING_BASE: u32 = 0x140000;

/// Flash erase granularity for the staging region.
const STAGING_ERASE_SIZE: u32 = 4096;

/// Minimum rollback counter accepted for an update.
const INSTALLED_ROLLBACK: u32 = 1;

// Firmware-update vendor public key, generated by `build.rs` (65-byte
// uncompressed SEC1 P-256 point). Override with `AEGIS_UPDATE_VENDOR_PUBKEY`.
include!(concat!(env!("OUT_DIR"), "/vendor_key.rs"));

// Board target selected at build time. The RP2350 and RP2354 variants share the
// same wiring; only the flash kind (external vs in-package) differs. Enabling
// two targets at once is a compile error by design (duplicate definition).
#[cfg(all(
    any(feature = "rp2350a", feature = "rp2350b"),
    any(feature = "rp2354a", feature = "rp2354b")
))]
compile_error!("select exactly one board target (rp2350a/b or rp2354a/b)");

#[cfg(all(
    not(any(feature = "rp2354a", feature = "rp2354b")),
    not(any(feature = "rp2350a", feature = "rp2350b"))
))]
compile_error!("select a board target: rp2350a, rp2350b, rp2354a or rp2354b");

#[cfg(any(feature = "rp2354a", feature = "rp2354b"))]
const BOARD_PROFILE: BoardProfile = BoardProfile::GENERIC_RP2354;

#[cfg(any(feature = "rp2350a", feature = "rp2350b"))]
const BOARD_PROFILE: BoardProfile = BoardProfile::GENERIC;

#[embassy_executor::main(
    executor = "board_generic_rp2350::embassy_rp::executor::Executor",
    entry = "cortex_m_rt::entry"
)]
async fn main(_spawner: Spawner) {
    let p = embassy_rp::init(Default::default());
    let Platform {
        mut board,
        usb,
        mut rng,
    } = Platform::<FLASH_SIZE>::new(p, &BOARD_PROFILE);

    let caps = board.capabilities();
    info!(
        "AegisToken {} boot: gpio={} fido_hid={} management_hid={}",
        aegis_core::VERSION,
        caps.gpio_count,
        caps.usb.fido_hid,
        caps.usb.management_hid,
    );
    info!(
        "device root key provisioned: {}",
        board_generic_rp2350::otp::read_root_key().is_ok()
    );
    if VENDOR_KEY_IS_DEV {
        info!("warning: development firmware-update vendor key in use");
    }
    let bootsel_held = board.bootsel_pressed();
    info!(
        "boot destination recovery={} (bootsel held: {})",
        aegis_core::state::boot_destination(bootsel_held) == aegis_core::ExecutionState::Recovery,
        bootsel_held
    );
    // Load the persisted configuration, falling back to factory defaults when
    // none exists or it no longer matches this device.
    let initial_config = load_config(&mut board, &caps);
    let mut management = ManagementService::new(caps, initial_config, LifecycleState::Factory);

    board.start_watchdog(WATCHDOG_TIMEOUT);

    selftest::run(&mut board, &mut rng);

    let Usb {
        device,
        keyboard,
        fido,
        management: management_hid,
    } = usb;
    let (fido_reader, fido_writer) = fido.split();
    let (management_reader, management_writer) = management_hid.split();

    join3(
        usb_supervisor(device),
        fido_task(fido_reader, fido_writer, &mut rng),
        join(
            housekeeping(
                management_reader,
                management_writer,
                &mut management,
                &mut board,
            ),
            keyboard_task(keyboard),
        ),
    )
    .await;
}

/// Hold the boot keyboard interface open without injecting keystrokes.
///
/// The interface is advertised during enumeration; this task only waits for the
/// interrupt IN endpoint to be enabled and then stays idle.
async fn keyboard_task(mut writer: KeyboardWriter) {
    writer.ready().await;
    core::future::pending::<()>().await;
}

/// Drive the USB device and honor soft-detach requests from the Management
/// channel.
///
/// `UsbDevice::run()` holds a mutable borrow of the device, so the Management
/// task cannot disable it directly. Instead the `SoftDetach` command signals
/// [`DETACH`]; when it fires we stop driving the device and disable the
/// peripheral, which the host observes as a clean removal.
async fn usb_supervisor(mut device: UsbDevice<'static, RpUsb>) -> ! {
    loop {
        match select(device.run(), DETACH.wait()).await {
            // `run()` never resolves; only the detach signal can win.
            Either::First(never) => match never {},
            Either::Second(()) => {
                device.disable().await;
                // Stay detached until the host re-enumerates (replug/power cycle).
                core::future::pending().await
            }
        }
    }
}

/// Load and validate the persisted configuration, or return the defaults.
fn load_config<const FLASH_SIZE: usize>(
    board: &mut Board<FLASH_SIZE>,
    capabilities: &aegis_core::DeviceCapabilities,
) -> DeviceConfig {
    let mut store = ConfigStorage::new(board.storage(), CONFIG_BASE, SLOT_SIZE);
    match store.load() {
        Ok(Some(config)) => {
            let context = ValidationContext {
                capabilities,
                lifecycle: LifecycleState::Factory,
            };
            if config.validate(&context).is_ok() {
                info!("configuration loaded from flash");
                return config;
            }
            info!("stored configuration invalid; using defaults");
        }
        Ok(None) => info!("no stored configuration; using defaults"),
        Err(_) => info!("configuration read failed; using defaults"),
    }
    DeviceConfig::official_defaults()
}

/// Persist the active configuration.
fn persist_config<const FLASH_SIZE: usize>(board: &mut Board<FLASH_SIZE>, config: &DeviceConfig) {
    let mut store = ConfigStorage::new(board.storage(), CONFIG_BASE, SLOT_SIZE);
    match store.commit(config) {
        Ok(sequence) => info!("configuration persisted (sequence {})", sequence),
        Err(_) => info!("configuration persistence failed"),
    }
}

/// Serve the CTAPHID transport and CTAP2 commands.
async fn fido_task(mut reader: FidoReader, mut writer: FidoWriter, rng: &mut HardwareRng) {
    let mut assembler = Assembler::new();
    let mut next_channel: u32 = 1;
    let mut store = MemoryCredentialStore::new();
    let mut client_pin = ClientPin::new();
    let mut buf = [0u8; ctaphid::REPORT_SIZE];

    loop {
        let Ok(_len) = reader.read(&mut buf).await else {
            continue;
        };
        let Ok(packet) = ctaphid::parse_report(&buf) else {
            continue;
        };
        let channel = match &packet {
            ctaphid::Packet::Init { channel, .. } | ctaphid::Packet::Cont { channel, .. } => {
                *channel
            }
        };

        match assembler.accept(packet) {
            Ok(Some(message)) => {
                handle_ctaphid(
                    &mut writer,
                    &mut next_channel,
                    &message,
                    &mut store,
                    &mut client_pin,
                    rng,
                )
                .await
            }
            Ok(None) => {}
            Err(_) => {
                let report = ctaphid::error_report(channel, CtapHidError::InvalidSeq);
                let _ = writer.write(&report).await;
            }
        }
    }
}

/// Handle one complete CTAPHID message.
async fn handle_ctaphid(
    writer: &mut FidoWriter,
    next_channel: &mut u32,
    message: &ctaphid::Message,
    store: &mut MemoryCredentialStore,
    client_pin: &mut ClientPin,
    rng: &mut HardwareRng,
) {
    match message.command {
        CtapHidCommand::Init => {
            // Response: nonce (8) | channel (4) | protocol (1) | version (3) | caps (1).
            // The INIT response is sent on the broadcast channel; the newly
            // assigned channel id is carried inside the payload.
            let mut response = [0u8; 17];
            let nonce_len = message.payload.len().min(8);
            response[..nonce_len].copy_from_slice(&message.payload[..nonce_len]);

            let channel = *next_channel;
            *next_channel = (*next_channel).wrapping_add(1);
            response[8..12].copy_from_slice(&channel.to_be_bytes());
            response[12] = ctaphid::PROTOCOL_VERSION;
            response[13] = 0; // major
            response[14] = 1; // minor
            response[15] = 0; // build
            response[16] = CTAPHID_CAPABILITIES;

            send_ctaphid(
                writer,
                ctaphid::BROADCAST_CHANNEL,
                CtapHidCommand::Init,
                &response,
            )
            .await;
        }
        CtapHidCommand::Ping => {
            send_ctaphid(
                writer,
                message.channel,
                CtapHidCommand::Ping,
                &message.payload,
            )
            .await;
        }
        CtapHidCommand::Cbor => {
            let mut out = [0u8; 512];
            let len = handle_ctap2(&message.payload, &mut out, store, client_pin, rng).await;
            if let Some(&command) = message.payload.first() {
                LAST_CTAP_COMMAND.store(command, core::sync::atomic::Ordering::Relaxed);
            }
            if let Some(&status) = out.first() {
                LAST_CTAP_STATUS.store(status, core::sync::atomic::Ordering::Relaxed);
            }
            send_ctaphid(writer, message.channel, CtapHidCommand::Cbor, &out[..len]).await;
        }
        CtapHidCommand::Msg => {
            let up = if u2f::requires_user_presence(&message.payload) {
                await_bootsel(PRESENCE_TIMING).await.is_ok()
            } else {
                false
            };
            let response = u2f::handle(&message.payload, store, up);
            let mut out = [0u8; u2f::MAX_RESPONSE + 2];
            let len = response.encode_into(&mut out);
            send_ctaphid(writer, message.channel, CtapHidCommand::Msg, &out[..len]).await;
        }
        CtapHidCommand::Wink => {
            // No response is defined for WINK.
        }
        _ => {
            let report = ctaphid::error_report(message.channel, CtapHidError::InvalidCmd);
            let _ = writer.write(&report).await;
        }
    }
}

/// Write a single-byte CTAP2 status response.
fn write_status(status: ctap2::Ctap2Status, out: &mut [u8]) -> usize {
    out[0] = status.code();
    1
}

/// Encode a CTAP2 response, prefixed by the success status byte, or a status on
/// failure. CTAP2 responses are `status || CBOR` (status `0x00` = success).
fn encode_response<T: minicbor::Encode<()>>(value: &T, out: &mut [u8]) -> usize {
    if out.is_empty() {
        return 0;
    }
    match aegis_core::codec::encode_into(value, &mut out[1..]) {
        Ok(len) => {
            out[0] = 0x00;
            1 + len
        }
        Err(_) => write_status(ctap2::Ctap2Status::Other, out),
    }
}

/// Handle a CTAP2 request; returns the response payload length.
///
/// On success this is the CBOR-encoded response; on error it is the single
/// status byte, which is itself valid CBOR. User presence is required for
/// credential creation and assertion; the BOOTSEL context rule is enforced by
/// only asking for presence on these FIDO commands.
async fn handle_ctap2(
    payload: &[u8],
    out: &mut [u8],
    store: &mut MemoryCredentialStore,
    client_pin: &mut ClientPin,
    rng: &mut HardwareRng,
) -> usize {
    let Some((&command, params)) = payload.split_first() else {
        return write_status(ctap2::Ctap2Status::InvalidLength, out);
    };

    match ctap2::parse_request(command, params) {
        Ok(Ctap2Request::GetInfo) => encode_response(&ctap2::GetInfoResponse::default(), out),
        Ok(Ctap2Request::MakeCredential(request)) => {
            let uv = request.pin_uv_auth_param.as_ref().is_some_and(|param| {
                client_pin.verify_pin_uv_auth_param(param, &request.client_data_hash)
            });
            let up = await_bootsel(PRESENCE_TIMING).await.is_ok();
            match authenticator::make_credential(store, rng, &request, up, uv) {
                Ok(response) => encode_response(&response, out),
                Err(status) => write_status(status, out),
            }
        }
        Ok(Ctap2Request::GetAssertion(request)) => {
            let uv = request.pin_uv_auth_param.as_ref().is_some_and(|param| {
                client_pin.verify_pin_uv_auth_param(param, &request.client_data_hash)
            });
            let up = await_bootsel(PRESENCE_TIMING).await.is_ok();
            match authenticator::get_assertion(store, rng, &request, up, uv) {
                Ok(response) => encode_response(&response, out),
                Err(status) => write_status(status, out),
            }
        }
        Ok(Ctap2Request::ClientPin) => match ClientPinRequest::parse(params) {
            Ok(request) => match request.sub_command {
                SUB_GET_RETRIES => encode_response(&client_pin.get_retries(store), out),
                SUB_GET_KEY_AGREEMENT => match client_pin.key_agreement(rng) {
                    Ok(response) => encode_response(&response, out),
                    Err(status) => write_status(status, out),
                },
                SUB_SET_PIN => match client_pin.set_pin(&request, store) {
                    Ok(()) => write_status(ctap2::Ctap2Status::Ok, out),
                    Err(status) => write_status(status, out),
                },
                SUB_GET_PIN_TOKEN | SUB_GET_PIN_UV_AUTH_TOKEN_WITH_PERMISSIONS => {
                    match client_pin.get_pin_token(&request, store, rng) {
                        Ok(response) => encode_response(&response, out),
                        Err(status) => write_status(status, out),
                    }
                }
                _ => write_status(ctap2::Ctap2Status::InvalidCommand, out),
            },
            Err(status) => write_status(status, out),
        },
        Ok(Ctap2Request::Reset) => {
            let up = await_bootsel(PRESENCE_TIMING).await.is_ok();
            match authenticator::reset(store, up) {
                Ok(()) => write_status(ctap2::Ctap2Status::Ok, out),
                Err(status) => write_status(status, out),
            }
        }
        Ok(Ctap2Request::CredentialManagement) => {
            match CredentialManagementRequest::parse(params) {
                Ok(request) => match request.sub_command {
                    authenticator::CRED_MGMT_GET_METADATA => {
                        encode_response(&authenticator::creds_metadata(store), out)
                    }
                    authenticator::CRED_MGMT_DELETE => match request.credential_id {
                        Some(id) => match authenticator::delete_credential(store, &id) {
                            Ok(()) => write_status(ctap2::Ctap2Status::Ok, out),
                            Err(status) => write_status(status, out),
                        },
                        None => write_status(ctap2::Ctap2Status::MissingParameter, out),
                    },
                    _ => write_status(ctap2::Ctap2Status::InvalidCommand, out),
                },
                Err(status) => write_status(status, out),
            }
        }
        Ok(_) => write_status(ctap2::Ctap2Status::InvalidCommand, out),
        Err(status) => write_status(status, out),
    }
}

/// Split a CTAPHID payload across initialization and continuation reports.
async fn send_ctaphid(
    writer: &mut FidoWriter,
    channel: u32,
    command: CtapHidCommand,
    payload: &[u8],
) {
    let first = payload.len().min(ctaphid::INIT_DATA_LEN);
    let Ok(report) =
        ctaphid::init_report(channel, command, payload.len() as u16, &payload[..first])
    else {
        return;
    };
    if writer.write(&report).await.is_err() {
        return;
    }

    let mut offset = first;
    let mut sequence = 0u8;
    while offset < payload.len() {
        let end = (offset + ctaphid::CONT_DATA_LEN).min(payload.len());
        let Ok(report) = ctaphid::cont_report(channel, sequence, &payload[offset..end]) else {
            return;
        };
        if writer.write(&report).await.is_err() {
            return;
        }
        offset = end;
        sequence = sequence.saturating_add(1) & 0x7F;
    }
}

/// Serve the Management HID protocol and keep the LED and watchdog alive.
async fn housekeeping<const FLASH_SIZE: usize>(
    mut reader: ManagementReader,
    mut writer: ManagementWriter,
    service: &mut ManagementService,
    board: &mut Board<FLASH_SIZE>,
) {
    let mut assembler = aegis_core::management::Assembler::new();
    let mut buf = [0u8; aegis_core::management::REPORT_SIZE];
    let mut update_handler = UpdateHandler::default();
    let mut led_on = false;

    loop {
        match select(reader.read(&mut buf), Timer::after_millis(500)).await {
            Either::First(Ok(_len)) => {
                let Ok(frame) = aegis_core::management::parse_report(&buf) else {
                    continue;
                };
                let Ok(Some(message)) = assembler.accept(frame) else {
                    continue;
                };

                // Transport body: one status byte followed by the payload.
                let mut body = [0u8; 513];
                let mut soft_detach = false;
                let (response_code, body_len) = if (update::CMD_BEGIN..=update::CMD_ABORT)
                    .contains(&message.command)
                {
                    let length = handle_update(
                        message.command,
                        &message.payload,
                        &mut update_handler,
                        board,
                        &mut body,
                    );
                    (message.command | 0x80, length)
                } else if message.command == CMD_GET_LAST_FIDO_STATUS {
                    body[0] = 0x00;
                    body[1] = LAST_CTAP_COMMAND.load(core::sync::atomic::Ordering::Relaxed);
                    body[2] = LAST_CTAP_STATUS.load(core::sync::atomic::Ordering::Relaxed);
                    (CMD_GET_LAST_FIDO_STATUS | 0x80, 3)
                } else {
                    let command = ManagementCommand::from_code(message.command);
                    let response = service.handle(command, &message.payload);
                    body[0] = response.status.code();
                    let length = 1 + response.payload.len();
                    body[1..length].copy_from_slice(&response.payload);
                    if command == ManagementCommand::CommitConfiguration && response.status.is_ok()
                    {
                        persist_config(board, service.config());
                    }
                    soft_detach =
                        command == ManagementCommand::SoftDetach && response.status.is_ok();
                    (command.response_code(), length)
                };
                send_management(&mut writer, response_code, &body[..body_len]).await;

                // Signal only after the acknowledgement has been transmitted, so
                // the host sees the reply before the device detaches.
                if soft_detach {
                    DETACH.signal(());
                }
            }
            Either::First(Err(_)) => {}
            Either::Second(()) => {
                led_on = !led_on;
                if let Some(led) = board.led() {
                    let behavior = if led_on {
                        LedBehavior::Solid
                    } else {
                        LedBehavior::Off
                    };
                    let _ = led.set_behavior(behavior);
                }
                board.feed_watchdog(WATCHDOG_TIMEOUT);
            }
        }
    }
}

/// In-flight firmware update session.
#[derive(Default)]
struct UpdateHandler {
    session: Option<UpdateSession>,
}

fn update_ok(out: &mut [u8]) -> usize {
    out[0] = 0;
    1
}

fn update_error(out: &mut [u8]) -> usize {
    out[0] = aegis_core::CoreError::FirmwareError.code();
    1
}

/// Handle a firmware-update management command.
fn handle_update<const FLASH_SIZE: usize>(
    command: u8,
    payload: &[u8],
    handler: &mut UpdateHandler,
    board: &mut Board<FLASH_SIZE>,
    out: &mut [u8],
) -> usize {
    match command {
        update::CMD_BEGIN => {
            match UpdateSession::begin(
                payload,
                &VENDOR_PUBLIC_KEY,
                INSTALLED_ROLLBACK,
                STAGING_BASE,
                STAGING_ERASE_SIZE,
                board.storage(),
            ) {
                Ok(session) => {
                    handler.session = Some(session);
                    update_ok(out)
                }
                Err(_) => update_error(out),
            }
        }
        update::CMD_WRITE => {
            let Some(session) = handler.session.as_mut() else {
                return update_error(out);
            };
            match session.write(board.storage(), payload) {
                Ok(()) => update_ok(out),
                Err(_) => update_error(out),
            }
        }
        update::CMD_FINISH => {
            let Some(session) = handler.session.take() else {
                return update_error(out);
            };
            match session.finish(board.storage()) {
                Ok(image) => {
                    info!(
                        "firmware update verified: {}.{}.{}",
                        image.version.major, image.version.minor, image.version.patch
                    );
                    update_ok(out)
                }
                Err(_) => update_error(out),
            }
        }
        update::CMD_ABORT => {
            handler.session = None;
            update_ok(out)
        }
        _ => update_error(out),
    }
}

/// Split a Management HID payload across initialization and continuation reports.
async fn send_management(writer: &mut ManagementWriter, command: u8, payload: &[u8]) {
    use aegis_core::management::PAYLOAD_PER_REPORT;

    let first = payload.len().min(PAYLOAD_PER_REPORT);
    let Ok(report) =
        aegis_core::management::init_report(command, payload.len() as u16, &payload[..first])
    else {
        return;
    };
    if writer.write(&report).await.is_err() {
        return;
    }

    let mut offset = first;
    let mut sequence = 0u16;
    while offset < payload.len() {
        let end = (offset + PAYLOAD_PER_REPORT).min(payload.len());
        let Ok(report) =
            aegis_core::management::cont_report(command, sequence, &payload[offset..end])
        else {
            return;
        };
        if writer.write(&report).await.is_err() {
            return;
        }
        offset = end;
        sequence += 1;
    }
}
